### PR TITLE
Need to install curl before first use. Fixes #36.

### LINKED ISSUE #36: Need to install curl before being able to run Ubuntu installer (which installs curl).
* `curl` is not installed on Ubuntu out of the box.
* It is installed as part of `rails-install-ubuntu.sh`, which has `sudo apt-get --ignore-missing install ... curl` .
* But it is already needed before that runs, namly, for `bash < <(curl ...)`

### PR DESCRIPTION
**Pull request by aknrdureegaesr**
Somewhat of a lame fix, but it will at least work.

### CODE REVIEW

**Comment by hsbt** [comment]
Thanks!

**Comment by vesan** [comment]
@aknrdureegaesr thanks for fixing it!

**Comment by aknrdureegaesr** [comment]
You are very welcome! I'm happy to support RailsGirls.

**Comment by aknrdureegaesr** [comment]
Will the fix also migrate to http://guides.railsgirls.com/install#setup-for-linux ?

**Pull request merged**
